---
resources:
- ../base
configMapGenerator:
- name: config
  literals:
  - env=staging
- name: credentials
  files:
  - credentials=creds.txt
secretGenerator:
- name: username
  literals:
  - username=admin
- name: region
  files:
  - region=region.txt
- name: password
  envs:
  - .env
